cask_args appdir: "/Applications"

brew "neovim" 
brew "ripgrep" 
brew "tmux" 
brew "tmuxinator" 
brew "nvm" 
brew "fd"
brew "jq"
brew "zig"

cask "font-hack-nerd-font"
cask "ghostty"

# python
brew "pyenv"

# zsh
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
